## Anotações referente a disciplina de Análise Exploratório de Dados e Visualização

In [13]:
temperatura = [12,34,3,7,8,444,3,3,25,6,778,8,444]
print(len(temperatura))
print( temperatura[2])
print(temperatura[-1])
print(temperatura[0:2])

13
3
444
[12, 34]

In [16]:
dicionario = {"cadeira":"madeira","numeros":[2,1]}
dicionario["cadeira"]

'madeira'

#### Laços

In [21]:
print([i for i in temperatura])

[12, 34, 3, 7, 8, 444, 3, 3, 25, 6, 778, 8, 444]

#### Função

In [23]:
def bomdia():
    return "Hello"
bomdia()

'Hello'

### Pandas

In [24]:
import pandas as pd

In [26]:
df=pd.read_csv("chamados_1746.csv")
df

,id_chamado,data_abertura,bairro,tipo,status,tempo_horas,nota_avaliacao
0,260001,2026-01-01,Botafogo,Buraco na via,Fechado,168.0,NaN
1,260002,2026-01-01,Santa Cruz,Buraco na via,Fechado,289.8,3.0
2,260003,2026-01-01,Realengo,Buraco na via,Fechado,86.7,NaN
3,260004,2026-01-01,Santa Cruz,Estacionamento irregular,Fechado,6.3,NaN
4,260005,2026-01-01,Campo Grande,Iluminação Pública,Aberto,NaN,NaN
...,...,...,...,...,...,...,...
1995,261996,2026-06-30,Realengo,Iluminação Pública,Fechado,40.1,NaN
1996,261997,2026-06-30,Realengo,Fiscalização de barulho,Fechado,7.7,2.0
1997,261998,2026-06-30,Tijuca,Fiscalização de barulho,Aberto,NaN,NaN
1998,261999,2026-06-30,Méier,Poda de árvore,Fechado,591.7,2.0
1999,262000,2026-06-30,Ipanema,Iluminação Pública,Fechado,45.6,4.0

In [39]:
print(df.shape)

(2000, 7)

In [42]:
print(df.describe())

          id_chamado  tempo_horas  nota_avaliacao
count    2000.000000  1628.000000     1089.000000
mean   261000.500000    89.861057        3.473829
std       577.494589   107.493007        1.002526
min    260001.000000     1.100000        1.000000
25%    260500.750000    12.575000        3.000000
50%    261000.500000    58.750000        4.000000
75%    261500.250000   119.100000        4.000000
max    262000.000000  1343.400000        5.000000

In [44]:
df.columns

Index(['id_chamado', 'data_abertura', 'bairro', 'tipo', 'status',
       'tempo_horas', 'nota_avaliacao'],
      dtype='object')

In [49]:
selecao=df[['data_abertura','bairro']]
selecao

     data_abertura        bairro
0       2026-01-01      Botafogo
1       2026-01-01    Santa Cruz
2       2026-01-01      Realengo
3       2026-01-01    Santa Cruz
4       2026-01-01  Campo Grande
...            ...           ...
1995    2026-06-30      Realengo
1996    2026-06-30      Realengo
1997    2026-06-30        Tijuca
1998    2026-06-30         Méier
1999    2026-06-30       Ipanema

[2000 rows x 2 columns]

In [53]:
selecao[['bairro']]

            bairro
0         Botafogo
1       Santa Cruz
2         Realengo
3       Santa Cruz
4     Campo Grande
...            ...
1995      Realengo
1996      Realengo
1997        Tijuca
1998         Méier
1999       Ipanema

[2000 rows x 1 columns]

In [55]:
df['tipo'].value_counts()

tipo
Iluminação Pública          453
Buraco na via               399
Remoção de entulho          374
Fiscalização de barulho     271
Estacionamento irregular    268
Poda de árvore              235
Name: count, dtype: int64

In [57]:
df['bairro'].value_counts()

bairro
Campo Grande       364
Santa Cruz         293
Copacabana         272
Realengo           239
Tijuca             218
Centro             163
Barra da Tijuca    116
Botafogo           104
Madureira           91
Méier               87
Ipanema             53
Name: count, dtype: int64

In [62]:
mascara = df["status"] == "Aberto"
df[mascara]

,id_chamado,data_abertura,bairro,tipo,status,tempo_horas,nota_avaliacao
4,260005,2026-01-01,Campo Grande,Iluminação Pública,Aberto,NaN,NaN
12,260013,2026-01-02,Madureira,Iluminação Pública,Aberto,NaN,NaN
14,260015,2026-01-02,Realengo,Fiscalização de barulho,Aberto,NaN,NaN
22,260023,2026-01-03,Campo Grande,Estacionamento irregular,Aberto,NaN,NaN
23,260024,2026-01-03,Campo Grande,Fiscalização de barulho,Aberto,NaN,NaN
...,...,...,...,...,...,...,...
1954,261955,2026-06-27,Realengo,Remoção de entulho,Aberto,NaN,NaN
1956,261957,2026-06-27,Ipanema,Iluminação Pública,Aberto,NaN,NaN
1980,261981,2026-06-30,Santa Cruz,Iluminação Pública,Aberto,NaN,NaN
1986,261987,2026-06-30,Copacabana,Buraco na via,Aberto,NaN,NaN
1997,261998,2026-06-30,Tijuca,Fiscalização de barulho,Aberto,NaN,NaN

np.int64(1695)